# Copyright (C) 2025-2026  David Ruff develop@ruffdd.de
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

[package]
name = "matrix-ldap-bridge-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
json = "0.12.4"
matrix-sdk = "0.16.0"
tokio = {version="1.49.0",features = ["full"]}
url = "2.5.8"

[[bin]]
name = "matrix-ldap-bridge-bot"
path = "src/main.rs"
